///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String assetsDart = 'assets/dart.pdf';
  static const String imagesImgAvatar3 = 'assets/images/img_avatar3.png';
  static const String imagesMypic = 'assets/images/mypic.jpg';
  static const String imagesPic1 = 'assets/images/pic1.jpg';
  static const String imagesPlaceholder = 'assets/images/placeholder.jpg';
  static const String myFlutterGalleryAssetsDart = 'assets/dart.pdf';
  static const String videosBouncingBall = 'assets/videos/bouncing_ball.mp4';

}
